const PARKING_DATA = [
    // 만안구
    { name: "안양역 공영주차장",       type: "outdoor",     area: "manan",  used: 105, total: 300, addr: "만안구 안양로 112" },
    { name: "안양6동2 노외주차장",     type: "outdoor",     area: "manan",  used: 64,  total: 180, addr: "만안구 안양로 298" },
    { name: "안양7동 노외주차장",      type: "outdoor",     area: "manan",  used: 87,  total: 120, addr: "만안구 냉천로 104" },
    { name: "안양8동 노외주차장",      type: "outdoor",     area: "manan",  used: 156, total: 170, addr: "만안구 만안로 82" },
    { name: "박달시장1 노외주차장",    type: "outdoor",     area: "manan",  used: 35,  total: 100, addr: "만안구 박달로 196" },
    { name: "박달시장2 노외주차장",    type: "outdoor",     area: "manan",  used: 68,  total: 90,  addr: "만안구 박달로 210" },
    { name: "공업부지 노외주차장",     type: "outdoor",     area: "manan",  used: 72,  total: 150, addr: "만안구 안양로 340" },
    { name: "비호교1 노외주차장",      type: "outdoor",     area: "manan",  used: 42,  total: 80,  addr: "만안구 석수로 55" },
    { name: "비호교2 노외주차장",      type: "outdoor",     area: "manan",  used: 55,  total: 70,  addr: "만안구 석수로 71" },
    { name: "관악역1 환승주차장",      type: "outdoor",     area: "manan",  used: 28,  total: 200, addr: "만안구 석수로 15" },
    { name: "관악역2 환승주차장",      type: "outdoor",     area: "manan",  used: 134, total: 180, addr: "만안구 석수로 25" },
    { name: "관악역3 환승주차장",      type: "outdoor",     area: "manan",  used: 45,  total: 120, addr: "만안구 석수로 35" },
    { name: "관악역4 환승주차장",      type: "outdoor",     area: "manan",  used: 95,  total: 100, addr: "만안구 석수로 45" },
    { name: "삼모루 노상주차장",       type: "street",      area: "manan",  used: 22,  total: 60,  addr: "만안구 안양로 200" },
    // 동안구
    { name: "범계역 공영주차장",       type: "outdoor",     area: "dongan", used: 216, total: 300, addr: "동안구 시민대로 180" },
    { name: "평촌지하 주차장",         type: "underground", area: "dongan", used: 320, total: 450, addr: "동안구 시민대로 235" },
    { name: "관양동 노외주차장",       type: "outdoor",     area: "dongan", used: 182, total: 200, addr: "동안구 관양동 1586" },
    { name: "충훈지하 주차장",         type: "underground", area: "dongan", used: 210, total: 380, addr: "동안구 평촌대로 200" },
    { name: "인덕원동 노외주차장",     type: "outdoor",     area: "dongan", used: 58,  total: 150, addr: "동안구 인덕원로 15" },
    { name: "동편마을지하 주차장",     type: "underground", area: "dongan", used: 270, total: 350, addr: "동안구 동편로 50" },
    { name: "스마트스퀘어지하 주차장", type: "underground", area: "dongan", used: 180, total: 400, addr: "동안구 시민대로 327" },
    { name: "4동 노외주차장",          type: "outdoor",     area: "dongan", used: 88,  total: 100, addr: "동안구 평촌대로 120" },
    { name: "호계3동 노외주차장",      type: "outdoor",     area: "dongan", used: 52,  total: 130, addr: "동안구 호계로 25" },
    { name: "일번가 노외주차장",       type: "outdoor",     area: "dongan", used: 77,  total: 110, addr: "동안구 평촌대로 85" },
    { name: "삼덕공원지하 주차장",     type: "underground", area: "dongan", used: 195, total: 300, addr: "동안구 관평로 200" },
    { name: "삼덕 노외주차장",         type: "outdoor",     area: "dongan", used: 32,  total: 80,  addr: "동안구 관평로 185" },
    { name: "호현마을1 노외주차장",    type: "outdoor",     area: "dongan", used: 44,  total: 90,  addr: "동안구 관양동 1700" },
    { name: "호현마을2 노외주차장",    type: "outdoor",     area: "dongan", used: 78,  total: 90,  addr: "동안구 관양동 1710" },
    { name: "샘모루초교지하 주차장",   type: "underground", area: "dongan", used: 110, total: 250, addr: "동안구 평촌대로 300" },
    { name: "개나리놀이터지하 주차장", type: "underground", area: "dongan", used: 150, total: 200, addr: "동안구 평촌대로 250" },
    { name: "덕현공원지하 주차장",     type: "underground", area: "dongan", used: 175, total: 220, addr: "동안구 평촌대로 180" },
    { name: "해동놀이터지하 주차장",   type: "underground", area: "dongan", used: 60,  total: 160, addr: "동안구 동안로 88" },
    { name: "화창초교지하 주차장",     type: "underground", area: "dongan", used: 130, total: 180, addr: "동안구 동안로 120" },
];
